# Generated by Django 5.2.7 on 2025-11-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="apis_user",
        ),
    ]
