# Generated by Django 5.2.7 on 2025-10-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='isFrontPage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='voicePreference',
            field=models.CharField(blank=True, default='shimmer', max_length=50, null=True),
        ),
    ]
