# Generated by Django 5.2.4 on 2025-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_alter_session_voicepreference_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="translated_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
