# Generated by Django 5.2.7 on 2025-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0003_session_translated_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="cover_tts_female",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="cover_tts_male",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="cover_tts_status",
            field=models.CharField(
                blank=True, default="pending", max_length=20, null=True
            ),
        ),
    ]
