# Generated by Django 5.2.7 on 2025-11-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_session_cover_tts_female_session_cover_tts_male_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="cover_tts_female",
        ),
        migrations.RemoveField(
            model_name="session",
            name="cover_tts_male",
        ),
        migrations.RemoveField(
            model_name="session",
            name="cover_tts_status",
        ),
    ]
