# Generated by Django 5.2.7 on 2025-11-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_session_translated_title'),
        ('apis', '0004_session_cover_tts_female_session_cover_tts_male_and_more'),
    ]

    operations = [
    ]
