# Generated by Django 5.2.7 on 2025-11-23 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_remove_session_cover_tts_female_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="session",
            name="totalWords",
            field=models.IntegerField(default=0),
        ),
    ]
